/*
 * PoS
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using PoS.Services.Services;
using PoS.Data;

using Microsoft.AspNetCore.Authorization;

namespace PoS.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class ItemServiceApiController : ControllerBase
    {
        IItemService _itemService;
        IServicesService _servicesService;

        public ItemServiceApiController(IItemService itemService, IServicesService servicesService)
        {
            _itemService = itemService;
            _servicesService = servicesService;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="itemId"></param>
        /// <response code="204">No Content</response>
        [HttpDelete]
        [Route("/ItemService/Item/{itemId}")]
        public async Task<IActionResult> DeleteItemAsync([FromRoute][Required] Guid itemId)
        {
            bool isDeleted = await _itemService.DeleteItemAsync(itemId);
            if(isDeleted)
            {
                return Ok();
            }

            return Problem();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="itemId"></param>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/ItemService/Item/{itemId}")]
        public async Task<IActionResult> GetItemAsync([FromRoute][Required] Guid itemId)
        {
            var result = await _itemService.GetItemByIdAsync(itemId);

            if(result != null)
            {
                return Ok(result);
            }

            return NoContent();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="itemId"></param>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPut]
        [Route("/ItemService/Item/{itemId}")]
        public async Task<IActionResult> UpdateItemAsync([FromRoute][Required]Guid itemId, [FromBody] Item body)
        {
            var item = await _itemService.UpdateItemAsync(itemId, body);
            if(item != null)
            {
                return Ok(item);
            }

            return NoContent();
        }

        ///// <summary>
        ///// 
        ///// </summary>
        ///// <param name="body"></param>
        ///// <response code="201">Created</response>
        [HttpPost]
        [Route("/ItemService/Item")]
        public async Task<IActionResult> CreateItemAsync([FromBody] Item item)
        {
            var newItem = await _itemService.CreateItemAsync(item);

            if(newItem != null)
            {
                return Ok(newItem);
            }

            return Problem();
        }

        ///// <summary>
        ///// 
        ///// </summary>
        ///// <param name="businessId"></param>
        ///// <param name="discountId"></param>
        ///// <param name="orderBy"></param>
        ///// <param name="sorting"></param>
        ///// <param name="pageIndex"></param>
        ///// <param name="pageSize"></param>
        ///// <response code="200">Success</response>
        [HttpGet]
        [Route("/ItemService/Items")]
        public async Task<IActionResult> GetItemsAsync()
        {
            var items = await _itemService.GetItemsAsync();

            if(items.Any())
            {
                return Ok(items);
            }

            return NoContent();
        }

        ///// <summary>
        ///// 
        ///// </summary>
        ///// <param name="body"></param>
        ///// <response code="201">Created</response>
        [HttpPost]
        [Route("/ItemService/Service")]
        public async Task<IActionResult> CreateServiceAsync([FromBody] Service service)
        {
            var newService = await _servicesService.CreateServiceAsync(service);
            if(newService != null)
            {
                return Ok(newService);
            }

            return Problem();
        }

        ///// <summary>
        ///// 
        ///// </summary>
        ///// <param name="serviceId"></param>
        ///// <response code="204">No Content</response>
        [HttpDelete]
        [Route("/ItemService/Service/{serviceId}")]
        public async Task<IActionResult> DeleteServiceAsync([FromRoute][Required] Guid serviceId)
        {
            bool isDeleted = await _servicesService.DeleteServiceAsync(serviceId);
            if(isDeleted)
            {
                return Ok();
            }

            return Problem();

        }

        ///// <summary>
        ///// 
        ///// </summary>
        ///// <param name="serviceId"></param>
        ///// <response code="200">Success</response>
        [HttpGet]
        [Route("/ItemService/Service/{serviceId}")]
        public async Task<IActionResult> GetServiceAsync([FromRoute][Required] Guid serviceId)
        {
            var service = await _servicesService.GetServiceByIdAsync(serviceId);
            if(service != null)
            {
                return Ok(service);
            }

            return NoContent();
        }

        ///// <summary>
        ///// 
        ///// </summary>
        ///// <param name="serviceId"></param>
        ///// <param name="body"></param>
        ///// <response code="200">Success</response>
        [HttpPut]
        [Route("/ItemService/Service/{serviceId}")]
        public async Task<IActionResult> UpdateServiceAsync([FromRoute][Required] Guid serviceId, [FromBody] Service body)
        {
            var service = await _servicesService.UpdateServiceAsync(serviceId, body);
            if(service != null)
            {
                return Ok(service);
            }

            return NoContent();
        }

        ///// <summary>
        ///// 
        ///// </summary>
        ///// <param name="businessId"></param>
        ///// <param name="staffId"></param>
        ///// <param name="discountId"></param>
        ///// <param name="orderBy"></param>
        ///// <param name="sorting"></param>
        ///// <param name="pageIndex"></param>
        ///// <param name="pageSize"></param>
        ///// <response code="200">Success</response>
        [HttpGet]
        [Route("/ItemService/Services")]
        public async Task<IActionResult> GetServicesAsync()
        {
            var services = await _servicesService.GetServicesAsync();
            if(services.Any())
            {
                return Ok(services);
            }

            return NoContent();
        }
    }
}
