/*
 * PoS
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class LoyaltyProgram : IEquatable<LoyaltyProgram>
    { 
        /// <summary>
        /// Gets or Sets Id
        /// </summary>

        [DataMember(Name="id")]
        public Guid? Id { get; set; }

        /// <summary>
        /// Gets or Sets BusinessId
        /// </summary>

        [DataMember(Name="businessId")]
        public Guid? BusinessId { get; set; }

        /// <summary>
        /// Gets or Sets PointsPerPurchase
        /// </summary>

        [DataMember(Name="pointsPerPurchase")]
        public double? PointsPerPurchase { get; set; }

        /// <summary>
        /// Gets or Sets RedemptionRules
        /// </summary>

        [DataMember(Name="redemptionRules")]
        public string RedemptionRules { get; set; }

        /// <summary>
        /// Gets or Sets SpecialBenefits
        /// </summary>

        [DataMember(Name="specialBenefits")]
        public string SpecialBenefits { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LoyaltyProgram {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  BusinessId: ").Append(BusinessId).Append("\n");
            sb.Append("  PointsPerPurchase: ").Append(PointsPerPurchase).Append("\n");
            sb.Append("  RedemptionRules: ").Append(RedemptionRules).Append("\n");
            sb.Append("  SpecialBenefits: ").Append(SpecialBenefits).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((LoyaltyProgram)obj);
        }

        /// <summary>
        /// Returns true if LoyaltyProgram instances are equal
        /// </summary>
        /// <param name="other">Instance of LoyaltyProgram to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LoyaltyProgram other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) && 
                (
                    BusinessId == other.BusinessId ||
                    BusinessId != null &&
                    BusinessId.Equals(other.BusinessId)
                ) && 
                (
                    PointsPerPurchase == other.PointsPerPurchase ||
                    PointsPerPurchase != null &&
                    PointsPerPurchase.Equals(other.PointsPerPurchase)
                ) && 
                (
                    RedemptionRules == other.RedemptionRules ||
                    RedemptionRules != null &&
                    RedemptionRules.Equals(other.RedemptionRules)
                ) && 
                (
                    SpecialBenefits == other.SpecialBenefits ||
                    SpecialBenefits != null &&
                    SpecialBenefits.Equals(other.SpecialBenefits)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (BusinessId != null)
                    hashCode = hashCode * 59 + BusinessId.GetHashCode();
                    if (PointsPerPurchase != null)
                    hashCode = hashCode * 59 + PointsPerPurchase.GetHashCode();
                    if (RedemptionRules != null)
                    hashCode = hashCode * 59 + RedemptionRules.GetHashCode();
                    if (SpecialBenefits != null)
                    hashCode = hashCode * 59 + SpecialBenefits.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(LoyaltyProgram left, LoyaltyProgram right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(LoyaltyProgram left, LoyaltyProgram right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
